version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
    command: npm run dev

volumes:
  redis_volume_data:
